USE MILAN;

CREATE TABLE ORD_MASTER (ORD_NO INT PRIMARY KEY, CUST_ID VARCHAR(30) , STATUS CHAR);
CREATE TABLE ORD_DTL(ORD_NO INT,PROD_CD VARCHAR(30),QTY INT);
CREATE TABLE  PROD_MASTER (PROD_CD VARCHAR(10) PRIMARY KEY,PROD_NAME VARCHAR(30),QTY_IN_STOCK INT,BOOKED_QTY INT);

INSERT INTO ORD_MASTER VALUES (1,'C1','P');
INSERT INTO ORD_DTL VALUES ( 1,'P1',100),(1,'P2',200);
INSERT INTO PROD_MASTER VALUES ('P1','Floppies',10000,1000),('P2','Printers',5000,600),('P3','Modems',3000,200);

SELECT * FROM ORD_MASTER;
SELECT * FROM ORD_DTL;
SELECT * FROM PROD_MASTER;


-- TRIGGER1
DELIMITER $$
CREATE TRIGGER QUE1 BEFORE INSERT ON ORD_DTL
FOR EACH ROW
BEGIN
UPDATE PROD_MASTER SET BOOKED_QTY=BOOKED_QTY+NEW.QTY WHERE PROD_CD=NEW.PROD_CD;
END $$

INSERT INTO ORD_DTL VALUES (1,'P3',300);

-- TRIGGER2 
DELIMITER $$ 
CREATE TRIGGER QUE2 BEFORE DELETE ON ORD_DTL
FOR EACH ROW 
BEGIN
UPDATE PROD_MASTER SET BOOKED_QTY=BOOKED_QTY-OLD.QTY WHERE PROD_CD=OLD.PROD_CD;
END $$

DELETE FROM ORD_DTL WHERE PROD_CD='P2';

CREATE TABLE DEPT_SAL (DEPT_NO INT,TOTAL_SALARY INT);
INSERT INTO DEPT_SAL VALUES (10,12000),(30,2000);
SELECT * FROM EMP;
SELECT * FROM DEPT_SAL;

DELIMITER $$
CREATE TRIGGER QUE3 AFTER INSERT ON EMP
FOR EACH ROW 
BEGIN
UPDATE DEPT_SAL SET TOTAL_SALARY =TOTAL_SALARY+ NEW.SAL WHERE DEPT_NO=NEW.DEPTNO;  
END $$  


INSERT INTO EMP VALUES(1007,'MILAN','UNEMPLOYED',1005,'2020-05-21',5000,10);

DELIMITER $$ 
CREATE TRIGGER QUE32 BEFORE DELETE ON EMP
FOR EACH ROW 
BEGIN 
UPDATE DEPT_SAL SET TOTAL_SALARY =TOTAL_SALARY - OLD.SAL WHERE DEPT_NO=OLD.DEPTNO;
END $$
DROP TRIGGER QUE32;
DELETE FROM EMP WHERE EMPNO = 1007;
